backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img
local_backend: true

collections:
  - name: "guide"
    label: "Guide"
    folder: "src/pages/guide"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "guide-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Contributors", name: "contributors", widget: "list", required: false, default: ""}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "student"
    label: "Student"
    folder: "src/pages/student"
    create: true
    identifier_field: "name"
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "student-info"}
      - {label: "Student Type", name: "studentType", widget: "select", options: ["Striker", "Special"]}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Image", name: "image", widget: image}
      - {label: "Portrait", name: "portrait", widget: image}
      - {label: "Rarity", name: "rarity", widget: "select", options: ["1", "2", "3"]}
      - {label: "Affiliation", name: "affiliation", widget: "select", options: ["Abydos", "Trinity", "Gehenna", "Millennium", "Red Winter", "Valkyrie", "Hyakkiyako", "Shanhaijing"], required: false, default: ""}
      - {label: "Weapon Type", name: "weaponType", widget: "select", options: ["HG", "SMG", "AR", "SR", "SG", "MG", "GL", "MT", "RG", "RF", "RL", "DualSMG", "DualSG", "MountMG"]}
      - label: "Equipment"
        name: "equipment"
        widget: "object"
        required: false
        default: ""
        fields:
        - {label: "Equipment 1", name: "equipment1", widget: "select", options: ["Hat", "Gloves", "Shoes"], required: false, default: ""}
        - {label: "Equipment 2", name: "equipment2", widget: "select", options: ["Bag", "Hairpin", "Badge"], required: false, default: ""}
        - {label: "Equipment 3", name: "equipment3", widget: "select", options: ["Necklace", "Watch", "Charm"], required: false, default: ""}
      - {label: "Role", name: "role", widget: "select", options: ["Attacker", "Supporter", "Tank", "Healer"], required: false, default: ""}
      - {label: "Position", name: "position", widget: "select", options: ["Front", "Middle", "Back", "None"], required: false, default: ""}
      - {label: "ATK Type", name: "atkType", widget: "select", options: ["Penetration", "Explosion", "Mystic"]}
      - {label: "DEF Type", name: "defType", widget: "select", options: ["Light Armour", "Heavy Armour", "Special Armour"]}
      - label: "Combat Environment"
        name: "combatEnvironment"
        widget: "object"
        fields:
        - {label: "Outdoor", name: "outdoor", widget: "select", options: ["S", "A", "B", "C", "D", "Unknown"]}
        - {label: "Urban", name: "urban", widget: "select", options: ["S", "A", "B", "C", "D", "Unknown"]}
        - {label: "Indoor", name: "indoor", widget: "select", options: ["S", "A", "B", "C", "D", "Unknown"]}
      - label: "EX Skill"
        name: "exSkill"
        widget: "object"
        required: false
        default: ""
        fields:
        - {label: "Cost", name: "exCost", widget: "number", value_type: "int", min: 0, max: 10, required: false, default: 0}
        - {label: "Lv1", name: "ex1", widget: "text", required: false, default: ""}
        - {label: "Lv2", name: "ex2", widget: "text", required: false, default: ""}
        - {label: "Lv3", name: "ex3", widget: "text", required: false, default: ""}
        - {label: "Lv4", name: "ex4", widget: "text", required: false, default: ""}
        - {label: "Lv5", name: "ex5", widget: "text", required: false, default: ""}
      - label: "Normal Skill"
        name: "normalSkill"
        widget: "object"
        required: false
        default: ""
        fields:
        - {label: "Lv1", name: "normal1", widget: "text", required: false, default: ""}
        - {label: "Lv2", name: "normal2", widget: "text", required: false, default: ""}
        - {label: "Lv3", name: "normal3", widget: "text", required: false, default: ""}
        - {label: "Lv4", name: "normal4", widget: "text", required: false, default: ""}
        - {label: "Lv5", name: "normal5", widget: "text", required: false, default: ""}
        - {label: "Lv6", name: "normal6", widget: "text", required: false, default: ""}
        - {label: "Lv7", name: "normal7", widget: "text", required: false, default: ""}
        - {label: "Lv8", name: "normal8", widget: "text", required: false, default: ""}
        - {label: "Lv9", name: "normal9", widget: "text", required: false, default: ""}
        - {label: "Lv10", name: "normal10", widget: "text", required: false, default: ""}
      - label: "Passive Skill"
        name: "passiveSkill"
        widget: "object"
        required: false
        default: ""
        fields:
        - {label: "Lv1", name: "passive1", widget: "text", required: false, default: ""}
        - {label: "Lv2", name: "passive2", widget: "text", required: false, default: ""}
        - {label: "Lv3", name: "passive3", widget: "text", required: false, default: ""}
        - {label: "Lv4", name: "passive4", widget: "text", required: false, default: ""}
        - {label: "Lv5", name: "passive5", widget: "text", required: false, default: ""}
        - {label: "Lv6", name: "passive6", widget: "text", required: false, default: ""}
        - {label: "Lv7", name: "passive7", widget: "text", required: false, default: ""}
        - {label: "Lv8", name: "passive8", widget: "text", required: false, default: ""}
        - {label: "Lv9", name: "passive9", widget: "text", required: false, default: ""}
        - {label: "Lv10", name: "passive10", widget: "text", required: false, default: ""}
      - label: "Sub Skill"
        name: "subSkill"
        widget: "object"
        required: false
        default: ""
        fields:
        - {label: "Lv1", name: "sub1", widget: "text", required: false, default: ""}
        - {label: "Lv2", name: "sub2", widget: "text", required: false, default: ""}
        - {label: "Lv3", name: "sub3", widget: "text", required: false, default: ""}
        - {label: "Lv4", name: "sub4", widget: "text", required: false, default: ""}
        - {label: "Lv5", name: "sub5", widget: "text", required: false, default: ""}
        - {label: "Lv6", name: "sub6", widget: "text", required: false, default: ""}
        - {label: "Lv7", name: "sub7", widget: "text", required: false, default: ""}
        - {label: "Lv8", name: "sub8", widget: "text", required: false, default: ""}
        - {label: "Lv9", name: "sub9", widget: "text", required: false, default: ""}
        - {label: "Lv10", name: "sub10", widget: "text", required: false, default: ""}
      - label: "Profile"
        name: "profile"
        widget: "object"
        required: false
        default: ""
        fields:
          - {label: "Full Name", name: "fullname", widget: "string", required: false, default: ""}
          - {label: "JP Name", name: "jpname", widget: "string", required: false, default: ""}
          - {label: "Club", name: "club", widget: "string", required: false, default: ""}
          - {label: "Age", name: "age", widget: "number", value_type: "int", min: 0, max: 999, required: false, default: 0}
          - {label: "Birthday", name: "birthday", widget: "string", required: false, default: ""}
          - {label: "Height", name: "height", widget: "number", value_type: "int", min: 0, max: 999, required: false, default: 0}
          - {label: "Hobbies", name: "hobbies", widget: "string", required: false, default: ""}
          - {label: "CV", name: "cv", widget: "string", required: false, default: ""}
          - {label: "Artist", name: "artist", widget: "string", required: false, default: ""}
          - {label: "Background Info", name: "info", widget: "text", required: false, default: ""}
      

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}